spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/color-of-today
    username: yj
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 3MB
logging.level:
  org.hibernate.SQL: debug
file.dir:
  C:/Users/yjffl/Desktop/Spring_study/color_images/